#!/bin/zsh

# Aliases for ls
alias ls='ls --human-readable --classify --color=auto --escape --group-directories-first'
alias la='ls --almost-all'
alias ll='ls --format=long --time-style=long-iso'
alias lla='ll --almost-all'

# Aliases for zmv
if which zmv &>|/dev/null; then
	alias zmv='zmv -o --verbose'
	which zcp &>|/dev/null && alias zcp='zcp -o --verbose'
	which zln &>|/dev/null && alias zln='zln -o --verbose'
	alias zmv-all_low="zmv '(*)' '\${1:l}'"
	alias zmv-space2underscore="zmv '(*)' '\${1// /_}'"
fi

# Filesystem Informations
alias df='df --human-readable'
alias du='du --human-readable'
alias free='free -moth'
alias lsblk="lsblk --output=NAME,RM,SIZE,RO,TYPE,FSTYPE,MOUNTPOINT,LABEL"
alias zstat='zstat -L -n -s'

# Misc aliases
alias chgrp='chgrp --change'
alias chmod='chmod --change'
alias chown='chown --change'
alias cp='cp --interactive --verbose'
alias ln='ln --verbose'
alias mkdir='mkdir --verbose --parents'
alias modprobe='modprobe --verbose'
alias mount='mount -v'
alias mv='mv --interactive --verbose'
alias rm='rm --verbose --one-file-system'
alias rmdir='rmdir --verbose'
which rsync &>|/dev/null && alias rsync='rsync --verbose --compress'
alias umount='umount -v'
which tree &>|/dev/null && alias tree="tree --dirsfirst -A"
