#!/bin/zsh
# Aliases for grep
if which grep &>|/dev/null; then
	alias egrep='egrep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias grep='grep --color=auto'
fi
which pgrep &>|/dev/null && alias pgrep='pgrep -l'
