#!/bin/zsh
autoload -Uz colors && colors

local toplevel="$(git rev-parse --show-toplevel 2>/dev/null)"

if [[ -n ${toplevel} ]]; then
	if [[ "${GIT_TOPLEVEL}" != "${toplevel}" ]]; then
		GIT_TOPLEVEL="${toplevel}"
	fi
else
	unset GIT_TOPLEVEL
fi
