#!/bin/zsh
# Dependencies:
# * coreutils
# * git
printhl() {
	print "${fg_bold[blue]}::${reset_color} ${bold_color}${1}${reset_color}"
}

local d

# Check for git
no_cmd_handler git || return 1

if [[ -z "${1}" ]]; then
	local first
	first=1
	for d in $(hash -d |grep "^git-remote" |cut -d "=" -f 2 |sort); do
		if [[ -d "${d}/.git" ]]; then
			if [[ ${first} -eq 0 ]]; then
				print ""
			else
				first=0
			fi
			printhl "${d:t}"
			(cd "${d}"; git pull)
		fi
	done
else
	until [[ -z "${1}" ]]; do
		if [[ -d "${1}/.git" ]]; then
			printhl "${1:t}"
			(cd "${1}"; git pull)
			if [[ ${#} -gt 0 ]]; then
				print ""
			fi
		fi
		shift
	done
fi

return 0
