#!/bin/zsh

local url
local urls

urls=("https://icanhazip.com" "https://ip.appspot.com")

# Make sure there is a internet connection
if ! ping -c 1 google.com &>| /dev/null; then
	return 1
fi

# Check for curl
no_cmd_handler curl || return 1

# Retrive IP address
for url in ${urls}; do
	if =curl -s ${url}; then
		return 0
	else
		continue
	fi
done

return 1
