#!/bin/sh
s=" | " # field separator

filename=$(basename -- "$1")
filesize=$(du --human-readable --dereference-args -- "$1" | cut -f 1)

if which identify >/dev/null 2>&1; then
	geometry=$(identify -format '%wx%h' ":$1[0]")
fi

echo "${filename}${geometry:+$s}${geometry}${filesize:+$s}${filesize}"
