#!/bin/zsh
if systemctl list-units --type target |grep -q graphical; then
	if [[ -z "$DISPLAY" && -n ${commands[startx]} && -f "${HOME}/.xinitrc" ]]; then
		# Correct SHLVL value
		export SHLVL=0

		# Start X session
		exec startx
	fi
fi
