#!/bin/zsh
# Set up prompt

# Add own prompts to fpath
if [[ -d ${HOME}/.zsh.d/prompt.d ]]; then
	fpath=(${HOME}/.zsh.d/prompt.d ${fpath})
	typeset -u fpath
fi

# Initialize prompt
promptinit

# Set prompt
prompt default
