#!/bin/zsh
# Colorize man when using less as pager

#LESS_TERMCAP_mb=$'\E[1;31m' \
#LESS_TERMCAP_md=$'\E[1;31m' \
#LESS_TERMCAP_me=$'\E[0m' \
#LESS_TERMCAP_se=$'\E[0m' \
#LESS_TERMCAP_so=$'\E[1;44;33m' \
#LESS_TERMCAP_ue=$'\E[0m' \
#LESS_TERMCAP_us=$'\E[1;32m' \
#=${0} ${@}

LESS_TERMCAP_mb=$'\e[01;32m'
LESS_TERMCAP_md=$'\e[0;34m'
LESS_TERMCAP_me=$'\e[0m'
LESS_TERMCAP_se=$'\e[0m'
LESS_TERMCAP_so=$'\e[0;30;43m'
LESS_TERMCAP_ue=$'\e[0m'
LESS_TERMCAP_us=$'\e[0;31m'
=${0} ${@}
